"""initial schema

Revision ID: 0f2ca374dda4
Revises: 
Create Date: 2025-12-26 00:59:12.184784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f2ca374dda4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('alternate_phone', sa.String(), nullable=True),
    sa.Column('id_proof_type', sa.String(), nullable=False),
    sa.Column('id_proof_number', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_proof_type', 'id_proof_number', name='uq_person_id_proof')
    )
    op.create_index(op.f('ix_persons_id'), 'persons', ['id'], unique=False)
    op.create_index(op.f('ix_persons_phone'), 'persons', ['phone'], unique=True)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('electricity_included', sa.Boolean(), nullable=False),
    sa.Column('water_included', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_room_number'), 'rooms', ['room_number'], unique=True)
    op.create_table('room_stays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=True),
    sa.Column('rent_type', sa.String(), nullable=False),
    sa.Column('rent_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('advance_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('caution_deposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('electricity_bill_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('water_bill_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_stays_id'), 'room_stays', ['id'], unique=False)
    op.create_index(op.f('ix_room_stays_room_id'), 'room_stays', ['room_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_stay_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_type', sa.String(), nullable=False),
    sa.Column('payment_mode', sa.String(), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['room_stay_id'], ['room_stays.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_room_stay_id'), 'payments', ['room_stay_id'], unique=False)
    op.create_table('room_stay_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_stay_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('joined_on', sa.Date(), nullable=False),
    sa.Column('left_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_stay_id'], ['room_stays.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_stay_persons_id'), 'room_stay_persons', ['id'], unique=False)
    op.create_index(op.f('ix_room_stay_persons_person_id'), 'room_stay_persons', ['person_id'], unique=False)
    op.create_index(op.f('ix_room_stay_persons_room_stay_id'), 'room_stay_persons', ['room_stay_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_stay_persons_room_stay_id'), table_name='room_stay_persons')
    op.drop_index(op.f('ix_room_stay_persons_person_id'), table_name='room_stay_persons')
    op.drop_index(op.f('ix_room_stay_persons_id'), table_name='room_stay_persons')
    op.drop_table('room_stay_persons')
    op.drop_index(op.f('ix_payments_room_stay_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_room_stays_room_id'), table_name='room_stays')
    op.drop_index(op.f('ix_room_stays_id'), table_name='room_stays')
    op.drop_table('room_stays')
    op.drop_index(op.f('ix_rooms_room_number'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_persons_phone'), table_name='persons')
    op.drop_index(op.f('ix_persons_id'), table_name='persons')
    op.drop_table('persons')
    # ### end Alembic commands ###
